version: '3'

services:
  elasticsearch: # Elasticsearch Instance
    container_name: sb-elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - esnet
  spoilerban:
    container_name: sb-spoilerban
    build: .
    ports:
      - 8084:8084

volumes:
  esdata01:
    driver: local

networks:
  esnet: